-- Generated by tools/ai_rig.py. Do not edit by hand.
-- Offsets are in pixels from the character's feet-center anchor.

HeroRig = {
	height = 96,
	frames = { head = 1, torso = 2, arm = 3, leg = 4 },
	head = { x = 3, y = -79 },
	torso = { x = 0, y = -51 },
	arm = { x = 0, y = -63 },
	leg = { x = 0, y = -39 },
	hipSpread = 2,
	shoulderSpread = 2,
}
