-- Generated by tools/ai_rig.py. Do not edit by hand.
-- Offsets are in pixels from the character's feet-center anchor.

HeroRig = {
	height = 72,
	frames = { head = 1, torso = 2, arm = 3, leg = 4 },
	head = { x = 2, y = -62 },
	torso = { x = 0, y = -38 },
	arm = { x = 0, y = -48 },
	leg = { x = 0, y = -29 },
	hipSpread = 1,
	shoulderSpread = 1,
}
