-- Generated by tools/ai_rig.py. Do not edit by hand.
-- Offsets are in pixels from each character's feet-center anchor.

Rigs = {
	frames = { head = 1, torso = 2, arm = 3, leg = 4 },
	hero = {
		height = 114,
		head = { x = 3, y = -93 },
		torso = { x = 0, y = -60 },
		arm = { x = 0, y = -75 },
		leg = { x = 0, y = -47 },
		hipSpread = 3,
		shoulderSpread = 4,
	},
	doc = {
		height = 106,
		head = { x = 3, y = -86 },
		torso = { x = 0, y = -56 },
		arm = { x = 0, y = -69 },
		leg = { x = 0, y = -43 },
		hipSpread = 3,
		shoulderSpread = 4,
	},
	engineer = {
		height = 116,
		head = { x = 3, y = -95 },
		torso = { x = 0, y = -62 },
		arm = { x = 0, y = -76 },
		leg = { x = 0, y = -48 },
		hipSpread = 3,
		shoulderSpread = 4,
	},
	security = {
		height = 111,
		head = { x = 3, y = -91 },
		torso = { x = 0, y = -59 },
		arm = { x = 0, y = -73 },
		leg = { x = 0, y = -46 },
		hipSpread = 4,
		shoulderSpread = 5,
	},
}
