#!/usr/bin/env python3
"""Generates every art asset plus the Lua tile atlas.

    python3 tools/gen_art.py

Outputs (all committed so the game builds without Python):
    source/images/tiles-table-32-32.png
    source/images/actors-table-32-32.png
    source/images/znomes-table-96-96.png
    source/scripts/world/atlas.lua
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from art_tiles import (
    GROUND_TILES, OBJECT_TILES, STRUCTURES, T, panel,
)
from art_znomes import FRAMES as ZNOME_FRAMES, SIZE as ZNOME_SIZE, ZNOMES
from canvas import (
    BLACK, CLEAR, WHITE, Canvas, dither_at, from_ascii, from_png, write_sheet,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES = os.path.join(ROOT, "source", "images")
PACK_ART = os.path.join(ROOT, "tools", "pack_art")


def pack(name):
    """Load a converted asset-pack element (legacy, unused)."""
    return from_png(os.path.join(PACK_ART, name + ".png"))


def pack_fn(name):
    return lambda: pack(name)


# --- build ---------------------------------------------------------------


def build_tiles():
    frames, names, flags, structures = [], {}, {}, {}

    def add(name, canvas, props):
        frames.append(canvas)
        idx = len(frames)  # image tables are 1-based
        names[name] = idx
        if props:
            flags[idx] = props
        return idx

    for name, fn, props in GROUND_TILES:
        add(name, fn(), props)
    for name, fn, props in OBJECT_TILES:
        add(name, fn(), props)

    for name, fn in STRUCTURES:
        canvas, meta = fn()
        grid, solid = [], []
        for ty in range(meta["h"]):
            for tx in range(meta["w"]):
                cell = canvas.sub(tx * T, ty * T, T, T)
                is_door = (tx, ty) in meta["doors"]
                idx = 0 if cell.is_blank() else add(
                    "%s_%d_%d" % (name, tx, ty), cell, {"solid": not is_door}
                )
                grid.append(idx)
                solid.append(0 if (is_door or idx == 0) else 1)
        structures[name] = {
            "w": meta["w"],
            "h": meta["h"],
            "tiles": grid,
            "solid": solid,
            "doors": meta["doors"],
        }
    return frames, names, flags, structures


def lua_atlas(names, flags, structures, count):
    out = ["-- Generated by tools/gen_art.py. Do not edit by hand.", "", "Atlas = {}", ""]
    out.append("Atlas.count = %d" % count)
    out.append("")
    out.append("Atlas.tile = {")
    for name in sorted(names):
        out.append("\t%s = %d," % (name, names[name]))
    out.append("}")
    out.append("")
    for prop in ("solid", "encounter"):
        out.append("Atlas.%s = {" % prop)
        for idx in sorted(i for i, p in flags.items() if p.get(prop)):
            out.append("\t[%d] = true," % idx)
        out.append("}")
        out.append("")
    out.append("Atlas.structures = {")
    for name in sorted(structures):
        s = structures[name]
        out.append("\t%s = {" % name)
        out.append("\t\tw = %d, h = %d," % (s["w"], s["h"]))
        out.append("\t\ttiles = { %s }," % ", ".join(str(v) for v in s["tiles"]))
        out.append("\t\tsolid = { %s }," % ", ".join(str(v) for v in s["solid"]))
        doors = ", ".join("{ x = %d, y = %d }" % (d[0], d[1]) for d in s["doors"])
        out.append("\t\tdoors = { %s }," % doors)
        out.append("\t},")
    out.append("}")
    out.append("")
    return "\n".join(out)


def scale2(c):
    out = Canvas(c.w * 2, c.h * 2)
    for y in range(c.h):
        for x in range(c.w):
            v = c.px[y][x]
            out.px[y * 2][x * 2] = v
            out.px[y * 2][x * 2 + 1] = v
            out.px[y * 2 + 1][x * 2] = v
            out.px[y * 2 + 1][x * 2 + 1] = v
    return out


def build_launcher(znome_frames):
    """Launcher card (350x155) and icon (32x32), 1-bit like everything else."""
    from PIL import Image, ImageDraw, ImageFont

    out = os.path.join(IMAGES, "launcher")
    os.makedirs(out, exist_ok=True)

    card = Canvas(350, 155, WHITE)
    card.dither_rect(0, 96, 350, 59, "d25")
    for i in range(0, 350, 40):
        card.line(i, 96, i + 18, 155, BLACK)
    card.outline_rect(0, 0, 350, 155, BLACK)
    card.blit(znome_frames[0 * ZNOME_FRAMES], 18, 54)
    card.blit(znome_frames[4 * ZNOME_FRAMES], 128, 56)
    card.blit(znome_frames[11 * ZNOME_FRAMES], 244, 52)
    panel(card, 40, 16, 270, 34)
    write_sheet(os.path.join(out, "card.png"), [card], 1, 350, 155)

    img = Image.open(os.path.join(out, "card.png")).convert("RGB")
    draw = ImageDraw.Draw(img)
    font = ImageFont.load_default()
    draw.text((150, 28), "ZNOME KOP", fill=(0, 0, 0), font=font)
    img.convert("RGBA").save(os.path.join(out, "card.png"))

    icon = Canvas(32, 32, WHITE)
    icon.blit(znome_frames[0], -32, -58)
    icon.outline_rect(0, 0, 32, 32, BLACK)
    write_sheet(os.path.join(out, "icon.png"), [icon], 1, 32, 32)


def main():
    os.makedirs(IMAGES, exist_ok=True)
    frames, names, flags, structures = build_tiles()
    write_sheet(os.path.join(IMAGES, "tiles-table-32-32.png"), frames, 8, T, T)

    znome_frames = []
    for _, fn in ZNOMES:
        znome_frames.extend(fn())
    write_sheet(
        os.path.join(IMAGES, "znomes-table-96-96.png"),
        znome_frames, ZNOME_FRAMES, ZNOME_SIZE, ZNOME_SIZE,
    )

    build_launcher(znome_frames)

    atlas = lua_atlas(names, flags, structures, len(frames))
    atlas += "\nAtlas.znomeFrames = %d\n\nAtlas.znomeSprite = {\n" % ZNOME_FRAMES
    for i, (name, _) in enumerate(ZNOMES):
        atlas += "\t%s = %d,\n" % (name, i * ZNOME_FRAMES + 1)
    atlas += "}\n"
    with open(os.path.join(ROOT, "source", "scripts", "world", "atlas.lua"), "w") as f:
        f.write(atlas)

    print("tiles: %d  znome frames: %d" % (len(frames), len(znome_frames)))


if __name__ == "__main__":
    main()
